/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  SystemBackupConfigResponse,
  SystemBackupConfigResponseFromJSON,
  SystemBackupConfigResponseToJSON,
  SystemBackupStatusResponse,
  SystemBackupStatusResponseFromJSON,
  SystemBackupStatusResponseToJSON,
  SystemPrivacyStatus,
  SystemPrivacyStatusFromJSON,
  SystemPrivacyStatusToJSON,
  SystemStatusResponse,
  SystemStatusResponseFromJSON,
  SystemStatusResponseToJSON,
} from '../models';

export interface UpdateSystemBackupConfigRequest {
  target: string;
  targetUser: string;
  targetPass: string;
  minAge: number;
}

export interface UpdateSystemPrivacyRequest {
  value: SystemPrivacyStatus;
}

/**
 *
 */
export class SystemApi extends runtime.BaseAPI {
  /**
   * Returns the system backup config.
   * Get system backup config
   */
  async getSystemBackupConfigRaw(): Promise<
    runtime.ApiResponse<SystemBackupConfigResponse>
  > {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/backup/config`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SystemBackupConfigResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns the system backup config.
   * Get system backup config
   */
  async getSystemBackupConfig(): Promise<SystemBackupConfigResponse> {
    const response = await this.getSystemBackupConfigRaw();
    return await response.value();
  }

  /**
   * Returns the system backup status.  If the list of backups is empty, this implies no backups have been made yet.
   * Get system backup status
   */
  async getSystemBackupStatusRaw(): Promise<
    runtime.ApiResponse<SystemBackupStatusResponse>
  > {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/backup/status`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SystemBackupStatusResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns the system backup status.  If the list of backups is empty, this implies no backups have been made yet.
   * Get system backup status
   */
  async getSystemBackupStatus(): Promise<SystemBackupStatusResponse> {
    const response = await this.getSystemBackupStatusRaw();
    return await response.value();
  }

  /**
   * Returns system privacy (new-version check) status.  Response:    - `true`: Private, new-version checks will not be performed   - `false`: Not private, new-version checks will be performed
   * Get system privacy status
   */
  async getSystemPrivacyStatusRaw(): Promise<runtime.ApiResponse<boolean>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/privacy`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Returns system privacy (new-version check) status.  Response:    - `true`: Private, new-version checks will not be performed   - `false`: Not private, new-version checks will be performed
   * Get system privacy status
   */
  async getSystemPrivacyStatus(): Promise<boolean> {
    const response = await this.getSystemPrivacyStatusRaw();
    return await response.value();
  }

  /**
   * Returns the system reboot status.  Response:    - `true`: A reboot is required   - `false`: A reboot is not required
   * Get system reboot status
   */
  async getSystemRebootStatusRaw(): Promise<runtime.ApiResponse<boolean>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/reboot`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Returns the system reboot status.  Response:    - `true`: A reboot is required   - `false`: A reboot is not required
   * Get system reboot status
   */
  async getSystemRebootStatus(): Promise<boolean> {
    const response = await this.getSystemRebootStatusRaw();
    return await response.value();
  }

  /**
   * Returns an array of statuses which can include headings.
   * Get system status
   */
  async getSystemStatusRaw(): Promise<
    runtime.ApiResponse<SystemStatusResponse>
  > {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/status`,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    });

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SystemStatusResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns an array of statuses which can include headings.
   * Get system status
   */
  async getSystemStatus(): Promise<SystemStatusResponse> {
    const response = await this.getSystemStatusRaw();
    return await response.value();
  }

  /**
   * Returns system (apt) updates.
   * Get system updates
   */
  async getSystemUpdatesRaw(): Promise<runtime.ApiResponse<string>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/updates`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Returns system (apt) updates.
   * Get system updates
   */
  async getSystemUpdates(): Promise<string> {
    const response = await this.getSystemUpdatesRaw();
    return await response.value();
  }

  /**
   * Returns Mail-in-a-Box upstream version.
   * Get system upstream version
   */
  async getSystemUpstreamVersionRaw(): Promise<runtime.ApiResponse<string>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/latest-upstream-version`,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Returns Mail-in-a-Box upstream version.
   * Get system upstream version
   */
  async getSystemUpstreamVersion(): Promise<string> {
    const response = await this.getSystemUpstreamVersionRaw();
    return await response.value();
  }

  /**
   * Returns installed Mail-in-a-Box version.
   * Get system version
   */
  async getSystemVersionRaw(): Promise<runtime.ApiResponse<string>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/version`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Returns installed Mail-in-a-Box version.
   * Get system version
   */
  async getSystemVersion(): Promise<string> {
    const response = await this.getSystemVersionRaw();
    return await response.value();
  }

  /**
   * Reboots the system.
   * Reboot system
   */
  async rebootSystemRaw(): Promise<runtime.ApiResponse<string>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/reboot`,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Reboots the system.
   * Reboot system
   */
  async rebootSystem(): Promise<string> {
    const response = await this.rebootSystemRaw();
    return await response.value();
  }

  /**
   * Updates the system backup config.
   * Update system backup config
   */
  async updateSystemBackupConfigRaw(
    requestParameters: UpdateSystemBackupConfigRequest
  ): Promise<runtime.ApiResponse<string>> {
    if (
      requestParameters.target === null ||
      requestParameters.target === undefined
    ) {
      throw new runtime.RequiredError(
        'target',
        'Required parameter requestParameters.target was null or undefined when calling updateSystemBackupConfig.'
      );
    }

    if (
      requestParameters.targetUser === null ||
      requestParameters.targetUser === undefined
    ) {
      throw new runtime.RequiredError(
        'targetUser',
        'Required parameter requestParameters.targetUser was null or undefined when calling updateSystemBackupConfig.'
      );
    }

    if (
      requestParameters.targetPass === null ||
      requestParameters.targetPass === undefined
    ) {
      throw new runtime.RequiredError(
        'targetPass',
        'Required parameter requestParameters.targetPass was null or undefined when calling updateSystemBackupConfig.'
      );
    }

    if (
      requestParameters.minAge === null ||
      requestParameters.minAge === undefined
    ) {
      throw new runtime.RequiredError(
        'minAge',
        'Required parameter requestParameters.minAge was null or undefined when calling updateSystemBackupConfig.'
      );
    }

    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const consumes: runtime.Consume[] = [
      { contentType: 'application/x-www-form-urlencoded' },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters.target !== undefined) {
      formParams.append('target', requestParameters.target as any);
    }

    if (requestParameters.targetUser !== undefined) {
      formParams.append('target_user', requestParameters.targetUser as any);
    }

    if (requestParameters.targetPass !== undefined) {
      formParams.append('target_pass', requestParameters.targetPass as any);
    }

    if (requestParameters.minAge !== undefined) {
      formParams.append('min_age', requestParameters.minAge as any);
    }

    const response = await this.request({
      path: `/system/backup/config`,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: formParams,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Updates the system backup config.
   * Update system backup config
   */
  async updateSystemBackupConfig(
    requestParameters: UpdateSystemBackupConfigRequest
  ): Promise<string> {
    const response = await this.updateSystemBackupConfigRaw(requestParameters);
    return await response.value();
  }

  /**
   * Updates system (apt) packages.
   * Update system packages
   */
  async updateSystemPackagesRaw(): Promise<runtime.ApiResponse<string>> {
    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const response = await this.request({
      path: `/system/update-packages`,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Updates system (apt) packages.
   * Update system packages
   */
  async updateSystemPackages(): Promise<string> {
    const response = await this.updateSystemPackagesRaw();
    return await response.value();
  }

  /**
   * Updates system privacy (new-version checks).  Request:    - `value: private`: Disable new version checks   - `value: off`: Enable new version checks
   * Update system privacy
   */
  async updateSystemPrivacyRaw(
    requestParameters: UpdateSystemPrivacyRequest
  ): Promise<runtime.ApiResponse<string>> {
    if (
      requestParameters.value === null ||
      requestParameters.value === undefined
    ) {
      throw new runtime.RequiredError(
        'value',
        'Required parameter requestParameters.value was null or undefined when calling updateSystemPrivacy.'
      );
    }

    const queryParameters: runtime.HTTPQuery = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters['Authorization'] =
        'Basic ' +
        btoa(this.configuration.username + ':' + this.configuration.password);
    }
    const consumes: runtime.Consume[] = [
      { contentType: 'application/x-www-form-urlencoded' },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters.value !== undefined) {
      formParams.append('value', requestParameters.value as any);
    }

    const response = await this.request({
      path: `/system/privacy`,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: formParams,
    });

    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    return new runtime[isJson ? 'JSONApiResponse' : 'TextApiResponse'](
      response
    ) as any;
  }

  /**
   * Updates system privacy (new-version checks).  Request:    - `value: private`: Disable new version checks   - `value: off`: Enable new version checks
   * Update system privacy
   */
  async updateSystemPrivacy(
    requestParameters: UpdateSystemPrivacyRequest
  ): Promise<string> {
    const response = await this.updateSystemPrivacyRaw(requestParameters);
    return await response.value();
  }
}
