/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DNSRecordType,
  DNSRecordTypeFromJSON,
  DNSRecordTypeFromJSONTyped,
  DNSRecordTypeToJSON,
} from './';

/**
 * Custom DNS record detail detail.
 * @export
 * @interface DNSCustomRecord
 */
export interface DNSCustomRecord {
  /**
   * Hostname format.
   * @type {string}
   * @memberof DNSCustomRecord
   */
  qname: string;
  /**
   *
   * @type {DNSRecordType}
   * @memberof DNSCustomRecord
   */
  rtype: DNSRecordType;
  /**
   *
   * @type {string}
   * @memberof DNSCustomRecord
   */
  value: string;
}

export function DNSCustomRecordFromJSON(json: any): DNSCustomRecord {
  return DNSCustomRecordFromJSONTyped(json, false);
}

export function DNSCustomRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSCustomRecord {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    qname: json['qname'],
    rtype: DNSRecordTypeFromJSON(json['rtype']),
    value: json['value'],
  };
}

export function DNSCustomRecordToJSON(value?: DNSCustomRecord | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    qname: value.qname,
    rtype: DNSRecordTypeToJSON(value.rtype),
    value: value.value,
  };
}
