/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DNSCustomRecord,
  DNSCustomRecordFromJSON,
  DNSCustomRecordFromJSONTyped,
  DNSCustomRecordToJSON,
} from './';

/**
 * Custom DNS records response.
 * @export
 * @interface DNSCustomRecordsResponse
 */
export interface DNSCustomRecordsResponse extends Array<DNSCustomRecord> {}

export function DNSCustomRecordsResponseFromJSON(
  json: any
): DNSCustomRecordsResponse {
  return DNSCustomRecordsResponseFromJSONTyped(json, false);
}

export function DNSCustomRecordsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSCustomRecordsResponse {
  return json;
}

export function DNSCustomRecordsResponseToJSON(
  value?: DNSCustomRecordsResponse | null
): any {
  return value;
}
