/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DNSDumpDomainRecord,
  DNSDumpDomainRecordFromJSON,
  DNSDumpDomainRecordFromJSONTyped,
  DNSDumpDomainRecordToJSON,
} from './';

/**
 * List of domain records.
 * @export
 * @interface DNSDumpDomainRecords
 */
export interface DNSDumpDomainRecords extends Array<DNSDumpDomainRecord> {}

export function DNSDumpDomainRecordsFromJSON(json: any): DNSDumpDomainRecords {
  return DNSDumpDomainRecordsFromJSONTyped(json, false);
}

export function DNSDumpDomainRecordsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSDumpDomainRecords {
  return json;
}

export function DNSDumpDomainRecordsToJSON(
  value?: DNSDumpDomainRecords | null
): any {
  return value;
}
