/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DNSDumpDomainRecords,
  DNSDumpDomainRecordsFromJSON,
  DNSDumpDomainRecordsFromJSONTyped,
  DNSDumpDomainRecordsToJSON,
} from './';

/**
 * A list of records per domain.
 *
 * The first item in the list is the domain and the second item is the list of records.
 * @export
 * @interface DNSDumpDomains
 */
export interface DNSDumpDomains extends Array<string | DNSDumpDomainRecords> {}

export function DNSDumpDomainsFromJSON(json: any): DNSDumpDomains {
  return DNSDumpDomainsFromJSONTyped(json, false);
}

export function DNSDumpDomainsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSDumpDomains {
  return json;
}

export function DNSDumpDomainsToJSON(value?: DNSDumpDomains | null): any {
  return value;
}
