/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DNSRecordType,
  DNSRecordTypeFromJSON,
  DNSRecordTypeFromJSONTyped,
  DNSRecordTypeToJSON,
} from './';

/**
 * Domain DNS record details.
 * @export
 * @interface DNSDumpDomainRecord
 */
export interface DNSDumpDomainRecord {
  /**
   *
   * @type {string}
   * @memberof DNSDumpDomainRecord
   */
  explanation: string;
  /**
   * Hostname format.
   * @type {string}
   * @memberof DNSDumpDomainRecord
   */
  qname: string;
  /**
   *
   * @type {DNSRecordType}
   * @memberof DNSDumpDomainRecord
   */
  rtype?: DNSRecordType;
  /**
   *
   * @type {string}
   * @memberof DNSDumpDomainRecord
   */
  value: string;
}

export function DNSDumpDomainRecordFromJSON(json: any): DNSDumpDomainRecord {
  return DNSDumpDomainRecordFromJSONTyped(json, false);
}

export function DNSDumpDomainRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSDumpDomainRecord {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    explanation: json['explanation'],
    qname: json['qname'],
    rtype: !exists(json, 'rtype')
      ? undefined
      : DNSRecordTypeFromJSON(json['rtype']),
    value: json['value'],
  };
}

export function DNSDumpDomainRecordToJSON(
  value?: DNSDumpDomainRecord | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    explanation: value.explanation,
    qname: value.qname,
    rtype: DNSRecordTypeToJSON(value.rtype),
    value: value.value,
  };
}
