/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  DNSDumpDomains,
  DNSDumpDomainsFromJSON,
  DNSDumpDomainsFromJSONTyped,
  DNSDumpDomainsToJSON,
} from './';

/**
 * DNS dump response.
 * @export
 * @interface DNSDumpResponse
 */
export interface DNSDumpResponse extends Array<DNSDumpDomains> {}

export function DNSDumpResponseFromJSON(json: any): DNSDumpResponse {
  return DNSDumpResponseFromJSONTyped(json, false);
}

export function DNSDumpResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSDumpResponse {
  return json;
}

export function DNSDumpResponseToJSON(value?: DNSDumpResponse | null): any {
  return value;
}
