/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Secondary nameserver/s add request.
 * @export
 * @interface DNSSecondaryNameserverAddRequest
 */
export interface DNSSecondaryNameserverAddRequest {
  /**
   * Hostnames separated with commas or spaces.
   * @type {string}
   * @memberof DNSSecondaryNameserverAddRequest
   */
  hostnames: string;
}

export function DNSSecondaryNameserverAddRequestFromJSON(
  json: any
): DNSSecondaryNameserverAddRequest {
  return DNSSecondaryNameserverAddRequestFromJSONTyped(json, false);
}

export function DNSSecondaryNameserverAddRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSSecondaryNameserverAddRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    hostnames: json['hostnames'],
  };
}

export function DNSSecondaryNameserverAddRequestToJSON(
  value?: DNSSecondaryNameserverAddRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    hostnames: value.hostnames,
  };
}
