/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * DNS update request.
 * @export
 * @interface DNSUpdateRequest
 */
export interface DNSUpdateRequest {
  /**
   * Force an update even if mailinabox detects no changes are required.
   * @type {number}
   * @memberof DNSUpdateRequest
   */
  force: number;
}

export function DNSUpdateRequestFromJSON(json: any): DNSUpdateRequest {
  return DNSUpdateRequestFromJSONTyped(json, false);
}

export function DNSUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSUpdateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    force: json['force'],
  };
}

export function DNSUpdateRequestToJSON(value?: DNSUpdateRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    force: value.force,
  };
}
