/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * DNS zones response.
 * @export
 * @interface DNSZonesResponse
 */
export interface DNSZonesResponse extends Array<string> {}

export function DNSZonesResponseFromJSON(json: any): DNSZonesResponse {
  return DNSZonesResponseFromJSONTyped(json, false);
}

export function DNSZonesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DNSZonesResponse {
  return json;
}

export function DNSZonesResponseToJSON(value?: DNSZonesResponse | null): any {
  return value;
}
