/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mail user set password request.
 * @export
 * @interface MailUserSetPasswordRequest
 */
export interface MailUserSetPasswordRequest {
  /**
   * Email format.
   * @type {string}
   * @memberof MailUserSetPasswordRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof MailUserSetPasswordRequest
   */
  password: string;
}

export function MailUserSetPasswordRequestFromJSON(
  json: any
): MailUserSetPasswordRequest {
  return MailUserSetPasswordRequestFromJSONTyped(json, false);
}

export function MailUserSetPasswordRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUserSetPasswordRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function MailUserSetPasswordRequestToJSON(
  value?: MailUserSetPasswordRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
  };
}
