/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  MailUserPrivilege,
  MailUserPrivilegeFromJSON,
  MailUserPrivilegeFromJSONTyped,
  MailUserPrivilegeToJSON,
} from './';

/**
 * Mail user add request.
 * @export
 * @interface MailUserAddRequest
 */
export interface MailUserAddRequest {
  /**
   * Email format.
   * @type {string}
   * @memberof MailUserAddRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof MailUserAddRequest
   */
  password: string;
  /**
   *
   * @type {MailUserPrivilege}
   * @memberof MailUserAddRequest
   */
  privileges: MailUserPrivilege;
}

export function MailUserAddRequestFromJSON(json: any): MailUserAddRequest {
  return MailUserAddRequestFromJSONTyped(json, false);
}

export function MailUserAddRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUserAddRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
    privileges: MailUserPrivilegeFromJSON(json['privileges']),
  };
}

export function MailUserAddRequestToJSON(
  value?: MailUserAddRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
    privileges: MailUserPrivilegeToJSON(value.privileges),
  };
}
