/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Mail user status.
 * @export
 * @enum {string}
 */
export enum MailUserStatus {
  Active = 'active',
  Inactive = 'inactive',
}

export function MailUserStatusFromJSON(json: any): MailUserStatus {
  return MailUserStatusFromJSONTyped(json, false);
}

export function MailUserStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUserStatus {
  return json as MailUserStatus;
}

export function MailUserStatusToJSON(value?: MailUserStatus | null): any {
  return value as any;
}
