/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  MailAlias,
  MailAliasFromJSON,
  MailAliasFromJSONTyped,
  MailAliasToJSON,
} from './';

/**
 * Mail aliases by domain.
 * @export
 * @interface MailAliasByDomain
 */
export interface MailAliasByDomain {
  /**
   * Hostname format.
   * @type {string}
   * @memberof MailAliasByDomain
   */
  domain: string;
  /**
   *
   * @type {Array<MailAlias>}
   * @memberof MailAliasByDomain
   */
  aliases: Array<MailAlias>;
}

export function MailAliasByDomainFromJSON(json: any): MailAliasByDomain {
  return MailAliasByDomainFromJSONTyped(json, false);
}

export function MailAliasByDomainFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailAliasByDomain {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    domain: json['domain'],
    aliases: (json['aliases'] as Array<any>).map(MailAliasFromJSON),
  };
}

export function MailAliasByDomainToJSON(value?: MailAliasByDomain | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    domain: value.domain,
    aliases: (value.aliases as Array<any>).map(MailAliasToJSON),
  };
}
