/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  MailUserPrivilege,
  MailUserPrivilegeFromJSON,
  MailUserPrivilegeFromJSONTyped,
  MailUserPrivilegeToJSON,
} from './';

/**
 * Mail user add privilege request.
 * @export
 * @interface MailUserAddPrivilegeRequest
 */
export interface MailUserAddPrivilegeRequest {
  /**
   * Email format.
   * @type {string}
   * @memberof MailUserAddPrivilegeRequest
   */
  email: string;
  /**
   *
   * @type {MailUserPrivilege}
   * @memberof MailUserAddPrivilegeRequest
   */
  privilege: MailUserPrivilege;
}

export function MailUserAddPrivilegeRequestFromJSON(
  json: any
): MailUserAddPrivilegeRequest {
  return MailUserAddPrivilegeRequestFromJSONTyped(json, false);
}

export function MailUserAddPrivilegeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUserAddPrivilegeRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    privilege: MailUserPrivilegeFromJSON(json['privilege']),
  };
}

export function MailUserAddPrivilegeRequestToJSON(
  value?: MailUserAddPrivilegeRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    privilege: MailUserPrivilegeToJSON(value.privilege),
  };
}
