/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  MailUser,
  MailUserFromJSON,
  MailUserFromJSONTyped,
  MailUserToJSON,
} from './';

/**
 * Mail users by domain.
 * @export
 * @interface MailUserByDomain
 */
export interface MailUserByDomain {
  /**
   * Hostname format.
   * @type {string}
   * @memberof MailUserByDomain
   */
  domain: string;
  /**
   *
   * @type {Array<MailUser>}
   * @memberof MailUserByDomain
   */
  users: Array<MailUser>;
}

export function MailUserByDomainFromJSON(json: any): MailUserByDomain {
  return MailUserByDomainFromJSONTyped(json, false);
}

export function MailUserByDomainFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUserByDomain {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    domain: json['domain'],
    users: (json['users'] as Array<any>).map(MailUserFromJSON),
  };
}

export function MailUserByDomainToJSON(value?: MailUserByDomain | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    domain: value.domain,
    users: (value.users as Array<any>).map(MailUserToJSON),
  };
}
