/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mail user remove request.
 * @export
 * @interface MailUserRemoveRequest
 */
export interface MailUserRemoveRequest {
  /**
   * Email format.
   * @type {string}
   * @memberof MailUserRemoveRequest
   */
  email: string;
}

export function MailUserRemoveRequestFromJSON(
  json: any
): MailUserRemoveRequest {
  return MailUserRemoveRequestFromJSONTyped(json, false);
}

export function MailUserRemoveRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUserRemoveRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
  };
}

export function MailUserRemoveRequestToJSON(
  value?: MailUserRemoveRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
  };
}
