/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mail aliases remove request.
 * @export
 * @interface MailAliasRemoveRequest
 */
export interface MailAliasRemoveRequest {
  /**
   * Email format.
   * @type {string}
   * @memberof MailAliasRemoveRequest
   */
  address: string;
}

export function MailAliasRemoveRequestFromJSON(
  json: any
): MailAliasRemoveRequest {
  return MailAliasRemoveRequestFromJSONTyped(json, false);
}

export function MailAliasRemoveRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailAliasRemoveRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    address: json['address'],
  };
}

export function MailAliasRemoveRequestToJSON(
  value?: MailAliasRemoveRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    address: value.address,
  };
}
