/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mail alias details.
 * @export
 * @interface MailAlias
 */
export interface MailAlias {
  /**
   * Email format.
   * @type {string}
   * @memberof MailAlias
   */
  address: string;
  /**
   * Email format.
   * @type {string}
   * @memberof MailAlias
   */
  addressDisplay: string;
  /**
   *
   * @type {Array<string>}
   * @memberof MailAlias
   */
  forwardsTo: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof MailAlias
   */
  permittedSenders: Array<string> | null;
  /**
   *
   * @type {boolean}
   * @memberof MailAlias
   */
  required: boolean;
}

export function MailAliasFromJSON(json: any): MailAlias {
  return MailAliasFromJSONTyped(json, false);
}

export function MailAliasFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailAlias {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    address: json['address'],
    addressDisplay: json['address_display'],
    forwardsTo: json['forwards_to'],
    permittedSenders: json['permitted_senders'],
    required: json['required'],
  };
}

export function MailAliasToJSON(value?: MailAlias | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    address: value.address,
    address_display: value.addressDisplay,
    forwards_to: value.forwardsTo,
    permitted_senders: value.permittedSenders,
    required: value.required,
  };
}
