/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response format (`application/json` or `text/html`).
 * @export
 * @enum {string}
 */
export enum MailUsersResponseFormat {
  Text = 'text',
  Json = 'json',
}

export function MailUsersResponseFormatFromJSON(
  json: any
): MailUsersResponseFormat {
  return MailUsersResponseFormatFromJSONTyped(json, false);
}

export function MailUsersResponseFormatFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUsersResponseFormat {
  return json as MailUsersResponseFormat;
}

export function MailUsersResponseFormatToJSON(
  value?: MailUsersResponseFormat | null
): any {
  return value as any;
}
