/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Mail alias upsert request.
 * @export
 * @interface MailAliasUpsertRequest
 */
export interface MailAliasUpsertRequest {
  /**
   * Set to `1` when updating an alias.
   * @type {number}
   * @memberof MailAliasUpsertRequest
   */
  updateIfExists: number;
  /**
   * Email format.
   * @type {string}
   * @memberof MailAliasUpsertRequest
   */
  address: string;
  /**
   * If adding a regular or catch-all alias, the format needs to be `email1@example.com`.
   * Multiple address can be separated by newlines or commas.
   *
   * If adding a domain alias, the format needs to be `@example.com`.
   * @type {string}
   * @memberof MailAliasUpsertRequest
   */
  forwardsTo: string;
  /**
   * Mail users that can send mail claiming to be from any address on the alias domain.
   * Multiple address can be separated by newlines or commas.
   *
   * Leave empty to allow any mail user listed in `forwards_to` to send mail claiming to be from any address on the alias domain.
   * @type {string}
   * @memberof MailAliasUpsertRequest
   */
  permittedSenders: string | null;
}

export function MailAliasUpsertRequestFromJSON(
  json: any
): MailAliasUpsertRequest {
  return MailAliasUpsertRequestFromJSONTyped(json, false);
}

export function MailAliasUpsertRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailAliasUpsertRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    updateIfExists: json['update_if_exists'],
    address: json['address'],
    forwardsTo: json['forwards_to'],
    permittedSenders: json['permitted_senders'],
  };
}

export function MailAliasUpsertRequestToJSON(
  value?: MailAliasUpsertRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    update_if_exists: value.updateIfExists,
    address: value.address,
    forwards_to: value.forwardsTo,
    permitted_senders: value.permittedSenders,
  };
}
