/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Mail user privilege.
 * @export
 * @enum {string}
 */
export enum MailUserPrivilege {
  Admin = 'admin',
  Empty = '',
}

export function MailUserPrivilegeFromJSON(json: any): MailUserPrivilege {
  return MailUserPrivilegeFromJSONTyped(json, false);
}

export function MailUserPrivilegeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUserPrivilege {
  return json as MailUserPrivilege;
}

export function MailUserPrivilegeToJSON(value?: MailUserPrivilege | null): any {
  return value as any;
}
