/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  MailUserPrivilege,
  MailUserPrivilegeFromJSON,
  MailUserPrivilegeFromJSONTyped,
  MailUserPrivilegeToJSON,
  MailUserStatus,
  MailUserStatusFromJSON,
  MailUserStatusFromJSONTyped,
  MailUserStatusToJSON,
} from './';

/**
 * Mail user details.
 * @export
 * @interface MailUser
 */
export interface MailUser {
  /**
   * Email format.
   * @type {string}
   * @memberof MailUser
   */
  email: string;
  /**
   *
   * @type {Array<MailUserPrivilege>}
   * @memberof MailUser
   */
  privileges: Array<MailUserPrivilege>;
  /**
   *
   * @type {MailUserStatus}
   * @memberof MailUser
   */
  status: MailUserStatus;
  /**
   *
   * @type {string}
   * @memberof MailUser
   */
  mailbox?: string;
}

export function MailUserFromJSON(json: any): MailUser {
  return MailUserFromJSONTyped(json, false);
}

export function MailUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MailUser {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    privileges: (json['privileges'] as Array<any>).map(
      MailUserPrivilegeFromJSON
    ),
    status: MailUserStatusFromJSON(json['status']),
    mailbox: !exists(json, 'mailbox') ? undefined : json['mailbox'],
  };
}

export function MailUserToJSON(value?: MailUser | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    privileges: (value.privileges as Array<any>).map(MailUserPrivilegeToJSON),
    status: MailUserStatusToJSON(value.status),
    mailbox: value.mailbox,
  };
}
