/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Me (user) authentication result.
 * @export
 * @enum {string}
 */
export enum MeAuthStatus {
  Ok = 'ok',
  Invalid = 'invalid',
}

export function MeAuthStatusFromJSON(json: any): MeAuthStatus {
  return MeAuthStatusFromJSONTyped(json, false);
}

export function MeAuthStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MeAuthStatus {
  return json as MeAuthStatus;
}

export function MeAuthStatusToJSON(value?: MeAuthStatus | null): any {
  return value as any;
}
