/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MfaStatusResponseNewMfa
 */
export interface MfaStatusResponseNewMfa {
  /**
   *
   * @type {string}
   * @memberof MfaStatusResponseNewMfa
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof MfaStatusResponseNewMfa
   */
  secret?: string;
  /**
   *
   * @type {string}
   * @memberof MfaStatusResponseNewMfa
   */
  qrCodeBase64?: string;
}

export function MfaStatusResponseNewMfaFromJSON(
  json: any
): MfaStatusResponseNewMfa {
  return MfaStatusResponseNewMfaFromJSONTyped(json, false);
}

export function MfaStatusResponseNewMfaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MfaStatusResponseNewMfa {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    secret: !exists(json, 'secret') ? undefined : json['secret'],
    qrCodeBase64: !exists(json, 'qr_code_base64')
      ? undefined
      : json['qr_code_base64'],
  };
}

export function MfaStatusResponseNewMfaToJSON(
  value?: MfaStatusResponseNewMfa | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    secret: value.secret,
    qr_code_base64: value.qrCodeBase64,
  };
}
