/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Generate SSL CSR request.
 * @export
 * @interface SSLCSRGenerateRequest
 */
export interface SSLCSRGenerateRequest {
  /**
   *
   * @type {string}
   * @memberof SSLCSRGenerateRequest
   */
  countrycode: string;
}

export function SSLCSRGenerateRequestFromJSON(
  json: any
): SSLCSRGenerateRequest {
  return SSLCSRGenerateRequestFromJSONTyped(json, false);
}

export function SSLCSRGenerateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SSLCSRGenerateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    countrycode: json['countrycode'],
  };
}

export function SSLCSRGenerateRequestToJSON(
  value?: SSLCSRGenerateRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    countrycode: value.countrycode,
  };
}
