/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  SSLCertificatesProvisionResponseRequests,
  SSLCertificatesProvisionResponseRequestsFromJSON,
  SSLCertificatesProvisionResponseRequestsFromJSONTyped,
  SSLCertificatesProvisionResponseRequestsToJSON,
} from './';

/**
 * SSL certificates provision response.
 * @export
 * @interface SSLCertificatesProvisionResponse
 */
export interface SSLCertificatesProvisionResponse {
  /**
   *
   * @type {Array<SSLCertificatesProvisionResponseRequests>}
   * @memberof SSLCertificatesProvisionResponse
   */
  requests: Array<SSLCertificatesProvisionResponseRequests>;
}

export function SSLCertificatesProvisionResponseFromJSON(
  json: any
): SSLCertificatesProvisionResponse {
  return SSLCertificatesProvisionResponseFromJSONTyped(json, false);
}

export function SSLCertificatesProvisionResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SSLCertificatesProvisionResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    requests: (json['requests'] as Array<any>).map(
      SSLCertificatesProvisionResponseRequestsFromJSON
    ),
  };
}

export function SSLCertificatesProvisionResponseToJSON(
  value?: SSLCertificatesProvisionResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    requests: (value.requests as Array<any>).map(
      SSLCertificatesProvisionResponseRequestsToJSON
    ),
  };
}
