/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SSLCertificatesProvisionResponseRequests
 */
export interface SSLCertificatesProvisionResponseRequests {
  /**
   *
   * @type {Array<string>}
   * @memberof SSLCertificatesProvisionResponseRequests
   */
  log: Array<string>;
  /**
   *
   * @type {string}
   * @memberof SSLCertificatesProvisionResponseRequests
   */
  result: SSLCertificatesProvisionResponseRequestsResultEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof SSLCertificatesProvisionResponseRequests
   */
  domains: Array<string>;
}

export function SSLCertificatesProvisionResponseRequestsFromJSON(
  json: any
): SSLCertificatesProvisionResponseRequests {
  return SSLCertificatesProvisionResponseRequestsFromJSONTyped(json, false);
}

export function SSLCertificatesProvisionResponseRequestsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SSLCertificatesProvisionResponseRequests {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    log: json['log'],
    result: json['result'],
    domains: json['domains'],
  };
}

export function SSLCertificatesProvisionResponseRequestsToJSON(
  value?: SSLCertificatesProvisionResponseRequests | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    log: value.log,
    result: value.result,
    domains: value.domains,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum SSLCertificatesProvisionResponseRequestsResultEnum {
  Installed = 'installed',
  Error = 'error',
  Skipped = 'skipped',
}
