/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SSLCertificatesProvisionResponseRequests
 */
export interface SSLCertificatesProvisionResponseRequests {
  /**
   *
   * @type {Array<string>}
   * @memberof SSLCertificatesProvisionResponseRequests
   */
  log: Array<string>;
  /**
   *
   * @type {string}
   * @memberof SSLCertificatesProvisionResponseRequests
   */
  result: SSLCertificatesProvisionResponseRequestsResultEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof SSLCertificatesProvisionResponseRequests
   */
  domains: Array<string>;
}

export function SSLCertificatesProvisionResponseRequestsFromJSON(
  json: any
): SSLCertificatesProvisionResponseRequests {
  return SSLCertificatesProvisionResponseRequestsFromJSONTyped(json, false);
}

export function SSLCertificatesProvisionResponseRequestsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SSLCertificatesProvisionResponseRequests {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    log: json['log'],
    result: json['result'],
    domains: json['domains'],
  };
}

export function SSLCertificatesProvisionResponseRequestsToJSON(
  value?: SSLCertificatesProvisionResponseRequests | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    log: value.log,
    result: value.result,
    domains: value.domains,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum SSLCertificatesProvisionResponseRequestsResultEnum {
  Installed = 'installed',
  Error = 'error',
  Skipped = 'skipped',
}
