/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * SSL status type.
 * @export
 * @enum {string}
 */
export enum SSLStatusType {
  Success = 'success',
  Danger = 'danger',
  NotApplicable = 'not-applicable',
}

export function SSLStatusTypeFromJSON(json: any): SSLStatusType {
  return SSLStatusTypeFromJSONTyped(json, false);
}

export function SSLStatusTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SSLStatusType {
  return json as SSLStatusType;
}

export function SSLStatusTypeToJSON(value?: SSLStatusType | null): any {
  return value as any;
}
