/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  SSLStatus,
  SSLStatusFromJSON,
  SSLStatusFromJSONTyped,
  SSLStatusToJSON,
} from './';

/**
 * SSL status response for all relevant domains.
 * @export
 * @interface SSLStatusResponse
 */
export interface SSLStatusResponse {
  /**
   *
   * @type {Array<string>}
   * @memberof SSLStatusResponse
   */
  canProvision: Array<string>;
  /**
   *
   * @type {Array<SSLStatus>}
   * @memberof SSLStatusResponse
   */
  status: Array<SSLStatus>;
}

export function SSLStatusResponseFromJSON(json: any): SSLStatusResponse {
  return SSLStatusResponseFromJSONTyped(json, false);
}

export function SSLStatusResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SSLStatusResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    canProvision: json['can_provision'],
    status: (json['status'] as Array<any>).map(SSLStatusFromJSON),
  };
}

export function SSLStatusResponseToJSON(value?: SSLStatusResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    can_provision: value.canProvision,
    status: (value.status as Array<any>).map(SSLStatusToJSON),
  };
}
