/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  StatusEntryExtra,
  StatusEntryExtraFromJSON,
  StatusEntryExtraFromJSONTyped,
  StatusEntryExtraToJSON,
  StatusEntryType,
  StatusEntryTypeFromJSON,
  StatusEntryTypeFromJSONTyped,
  StatusEntryTypeToJSON,
} from './';

/**
 * System status entry.
 * @export
 * @interface StatusEntry
 */
export interface StatusEntry {
  /**
   *
   * @type {StatusEntryType}
   * @memberof StatusEntry
   */
  type: StatusEntryType;
  /**
   *
   * @type {string}
   * @memberof StatusEntry
   */
  text: string;
  /**
   *
   * @type {Array<StatusEntryExtra>}
   * @memberof StatusEntry
   */
  extra: Array<StatusEntryExtra>;
}

export function StatusEntryFromJSON(json: any): StatusEntry {
  return StatusEntryFromJSONTyped(json, false);
}

export function StatusEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StatusEntry {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: StatusEntryTypeFromJSON(json['type']),
    text: json['text'],
    extra: (json['extra'] as Array<any>).map(StatusEntryExtraFromJSON),
  };
}

export function StatusEntryToJSON(value?: StatusEntry | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: StatusEntryTypeToJSON(value.type),
    text: value.text,
    extra: (value.extra as Array<any>).map(StatusEntryExtraToJSON),
  };
}
