/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  StatusEntryExtra,
  StatusEntryExtraFromJSON,
  StatusEntryExtraFromJSONTyped,
  StatusEntryExtraToJSON,
  StatusEntryType,
  StatusEntryTypeFromJSON,
  StatusEntryTypeFromJSONTyped,
  StatusEntryTypeToJSON,
} from './';

/**
 * System status entry.
 * @export
 * @interface StatusEntry
 */
export interface StatusEntry {
  /**
   *
   * @type {StatusEntryType}
   * @memberof StatusEntry
   */
  type: StatusEntryType;
  /**
   *
   * @type {string}
   * @memberof StatusEntry
   */
  text: string;
  /**
   *
   * @type {Array<StatusEntryExtra>}
   * @memberof StatusEntry
   */
  extra: Array<StatusEntryExtra>;
}

export function StatusEntryFromJSON(json: any): StatusEntry {
  return StatusEntryFromJSONTyped(json, false);
}

export function StatusEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StatusEntry {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: StatusEntryTypeFromJSON(json['type']),
    text: json['text'],
    extra: (json['extra'] as Array<any>).map(StatusEntryExtraFromJSON),
  };
}

export function StatusEntryToJSON(value?: StatusEntry | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: StatusEntryTypeToJSON(value.type),
    text: value.text,
    extra: (value.extra as Array<any>).map(StatusEntryExtraToJSON),
  };
}
