/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Backup config response.
 * @export
 * @interface SystemBackupConfigResponse
 */
export interface SystemBackupConfigResponse {
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  encPwFile: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  fileTargetDirectory: string;
  /**
   *
   * @type {number}
   * @memberof SystemBackupConfigResponse
   */
  minAgeInDays: number;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  sshPubKey: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  target: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  targetUser?: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  targetPass?: string;
}

export function SystemBackupConfigResponseFromJSON(
  json: any
): SystemBackupConfigResponse {
  return SystemBackupConfigResponseFromJSONTyped(json, false);
}

export function SystemBackupConfigResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SystemBackupConfigResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    encPwFile: json['enc_pw_file'],
    fileTargetDirectory: json['file_target_directory'],
    minAgeInDays: json['min_age_in_days'],
    sshPubKey: json['ssh_pub_key'],
    target: json['target'],
    targetUser: !exists(json, 'target_user') ? undefined : json['target_user'],
    targetPass: !exists(json, 'target_pass') ? undefined : json['target_pass'],
  };
}

export function SystemBackupConfigResponseToJSON(
  value?: SystemBackupConfigResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    enc_pw_file: value.encPwFile,
    file_target_directory: value.fileTargetDirectory,
    min_age_in_days: value.minAgeInDays,
    ssh_pub_key: value.sshPubKey,
    target: value.target,
    target_user: value.targetUser,
    target_pass: value.targetPass,
  };
}
