/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Backup config response.
 * @export
 * @interface SystemBackupConfigResponse
 */
export interface SystemBackupConfigResponse {
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  encPwFile: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  fileTargetDirectory: string;
  /**
   *
   * @type {number}
   * @memberof SystemBackupConfigResponse
   */
  minAgeInDays: number;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  sshPubKey: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  target: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  targetUser?: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigResponse
   */
  targetPass?: string;
}

export function SystemBackupConfigResponseFromJSON(
  json: any
): SystemBackupConfigResponse {
  return SystemBackupConfigResponseFromJSONTyped(json, false);
}

export function SystemBackupConfigResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SystemBackupConfigResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    encPwFile: json['enc_pw_file'],
    fileTargetDirectory: json['file_target_directory'],
    minAgeInDays: json['min_age_in_days'],
    sshPubKey: json['ssh_pub_key'],
    target: json['target'],
    targetUser: !exists(json, 'target_user') ? undefined : json['target_user'],
    targetPass: !exists(json, 'target_pass') ? undefined : json['target_pass'],
  };
}

export function SystemBackupConfigResponseToJSON(
  value?: SystemBackupConfigResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    enc_pw_file: value.encPwFile,
    file_target_directory: value.fileTargetDirectory,
    min_age_in_days: value.minAgeInDays,
    ssh_pub_key: value.sshPubKey,
    target: value.target,
    target_user: value.targetUser,
    target_pass: value.targetPass,
  };
}
