/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Backup config update request.
 * @export
 * @interface SystemBackupConfigUpdateRequest
 */
export interface SystemBackupConfigUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigUpdateRequest
   */
  target: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigUpdateRequest
   */
  targetUser: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupConfigUpdateRequest
   */
  targetPass: string;
  /**
   *
   * @type {number}
   * @memberof SystemBackupConfigUpdateRequest
   */
  minAge: number;
}

export function SystemBackupConfigUpdateRequestFromJSON(
  json: any
): SystemBackupConfigUpdateRequest {
  return SystemBackupConfigUpdateRequestFromJSONTyped(json, false);
}

export function SystemBackupConfigUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SystemBackupConfigUpdateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    target: json['target'],
    targetUser: json['target_user'],
    targetPass: json['target_pass'],
    minAge: json['min_age'],
  };
}

export function SystemBackupConfigUpdateRequestToJSON(
  value?: SystemBackupConfigUpdateRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    target: value.target,
    target_user: value.targetUser,
    target_pass: value.targetPass,
    min_age: value.minAge,
  };
}
