/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  SystemBackupStatus,
  SystemBackupStatusFromJSON,
  SystemBackupStatusFromJSONTyped,
  SystemBackupStatusToJSON,
} from './';

/**
 * Backup status response. Lists the status for all backups.
 * @export
 * @interface SystemBackupStatusResponse
 */
export interface SystemBackupStatusResponse {
  /**
   *
   * @type {Array<SystemBackupStatus>}
   * @memberof SystemBackupStatusResponse
   */
  backups?: Array<SystemBackupStatus>;
  /**
   *
   * @type {number}
   * @memberof SystemBackupStatusResponse
   */
  unmatchedFileSize: number;
  /**
   *
   * @type {string}
   * @memberof SystemBackupStatusResponse
   */
  error?: string;
}

export function SystemBackupStatusResponseFromJSON(
  json: any
): SystemBackupStatusResponse {
  return SystemBackupStatusResponseFromJSONTyped(json, false);
}

export function SystemBackupStatusResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SystemBackupStatusResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    backups: !exists(json, 'backups')
      ? undefined
      : (json['backups'] as Array<any>).map(SystemBackupStatusFromJSON),
    unmatchedFileSize: json['unmatched_file_size'],
    error: !exists(json, 'error') ? undefined : json['error'],
  };
}

export function SystemBackupStatusResponseToJSON(
  value?: SystemBackupStatusResponse | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    backups:
      value.backups === undefined
        ? undefined
        : (value.backups as Array<any>).map(SystemBackupStatusToJSON),
    unmatched_file_size: value.unmatchedFileSize,
    error: value.error,
  };
}
