/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Backup status details.
 * @export
 * @interface SystemBackupStatus
 */
export interface SystemBackupStatus {
  /**
   *
   * @type {Date}
   * @memberof SystemBackupStatus
   */
  date: Date;
  /**
   *
   * @type {string}
   * @memberof SystemBackupStatus
   */
  dateDelta: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupStatus
   */
  dateStr: string;
  /**
   *
   * @type {string}
   * @memberof SystemBackupStatus
   */
  deletedIn?: string;
  /**
   *
   * @type {boolean}
   * @memberof SystemBackupStatus
   */
  full: boolean;
  /**
   *
   * @type {number}
   * @memberof SystemBackupStatus
   */
  size: number;
  /**
   *
   * @type {number}
   * @memberof SystemBackupStatus
   */
  volumes: number;
}

export function SystemBackupStatusFromJSON(json: any): SystemBackupStatus {
  return SystemBackupStatusFromJSONTyped(json, false);
}

export function SystemBackupStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SystemBackupStatus {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    date: new Date(json['date']),
    dateDelta: json['date_delta'],
    dateStr: json['date_str'],
    deletedIn: !exists(json, 'deleted_in') ? undefined : json['deleted_in'],
    full: json['full'],
    size: json['size'],
    volumes: json['volumes'],
  };
}

export function SystemBackupStatusToJSON(
  value?: SystemBackupStatus | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    date: value.date.toISOString(),
    date_delta: value.dateDelta,
    date_str: value.dateStr,
    deleted_in: value.deletedIn,
    full: value.full,
    size: value.size,
    volumes: value.volumes,
  };
}
