/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.46.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * System privacy status.
 * @export
 * @enum {string}
 */
export enum SystemPrivacyStatus {
  Private = 'private',
  Off = 'off',
}

export function SystemPrivacyStatusFromJSON(json: any): SystemPrivacyStatus {
  return SystemPrivacyStatusFromJSONTyped(json, false);
}

export function SystemPrivacyStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SystemPrivacyStatus {
  return json as SystemPrivacyStatus;
}

export function SystemPrivacyStatusToJSON(
  value?: SystemPrivacyStatus | null
): any {
  return value as any;
}
