/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.
 *
 * The version of the OpenAPI document: 0.47.0
 * Contact: contact@mailinabox.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Web domain details.
 * @export
 * @interface WebDomain
 */
export interface WebDomain {
  /**
   *
   * @type {string}
   * @memberof WebDomain
   */
  customRoot: string;
  /**
   * Hostname format.
   * @type {string}
   * @memberof WebDomain
   */
  domain: string;
  /**
   *
   * @type {string}
   * @memberof WebDomain
   */
  root: string;
  /**
   *
   * @type {Array<string>}
   * @memberof WebDomain
   */
  sslCertificate: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof WebDomain
   */
  staticEnabled: boolean;
}

export function WebDomainFromJSON(json: any): WebDomain {
  return WebDomainFromJSONTyped(json, false);
}

export function WebDomainFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WebDomain {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    customRoot: json['custom_root'],
    domain: json['domain'],
    root: json['root'],
    sslCertificate: json['ssl_certificate'],
    staticEnabled: json['static_enabled'],
  };
}

export function WebDomainToJSON(value?: WebDomain | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    custom_root: value.customRoot,
    domain: value.domain,
    root: value.root,
    ssl_certificate: value.sslCertificate,
    static_enabled: value.staticEnabled,
  };
}
