/* tslint:disable */
/* eslint-disable */
/**
 * Mail-in-a-Box
 * Mail-in-a-Box API HTTP specification.  # Introduction This API is documented in [**OpenAPI format**](http://spec.openapis.org/oas/v3.0.3). ([View the full HTTP specification](https://raw.githubusercontent.com/mail-in-a-box/mailinabox/api-spec/api/mailinabox.yml).)  All endpoints are relative to `https://{host}/admin` and are secured with [`Basic Access` authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). If you have multi-factor authentication enabled, authentication with a `user:password` combination will fail unless a valid OTP is supplied via the `x-auth-token` header. Authentication via a `user:user_key` pair is possible without the header being present.
 *
 * The version of the OpenAPI document: 0.51.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Web domain details.
 * @export
 * @interface WebDomain
 */
export interface WebDomain {
  /**
   *
   * @type {string}
   * @memberof WebDomain
   */
  customRoot: string;
  /**
   * Hostname format.
   * @type {string}
   * @memberof WebDomain
   */
  domain: string;
  /**
   *
   * @type {string}
   * @memberof WebDomain
   */
  root: string;
  /**
   *
   * @type {Array<string>}
   * @memberof WebDomain
   */
  sslCertificate: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof WebDomain
   */
  staticEnabled: boolean;
}

export function WebDomainFromJSON(json: any): WebDomain {
  return WebDomainFromJSONTyped(json, false);
}

export function WebDomainFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WebDomain {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    customRoot: json['custom_root'],
    domain: json['domain'],
    root: json['root'],
    sslCertificate: json['ssl_certificate'],
    staticEnabled: json['static_enabled'],
  };
}

export function WebDomainToJSON(value?: WebDomain | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    custom_root: value.customRoot,
    domain: value.domain,
    root: value.root,
    ssl_certificate: value.sslCertificate,
    static_enabled: value.staticEnabled,
  };
}
